apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-notify-annotation
  annotations:
    k8s.cronitor.io/cronitor-id: ''
    k8s.cronitor.io/cronitor-notify: 'devops-slack, infra-teams'
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args: [/bin/sh, -c, date ; sleep 5 ; echo Hello from k8s]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
